config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index" #home ali é controller, index ali é action
  resources :settings, only: [:index] do 
    # member do # cancel_setting DELETE /settings/:id/cancel(.:format) | pode ter varia aquiu seria para deletar um usuario da para brincar com isso
    #   delete :cancel 
    # end

    collection do # member "setting PATCH /settings/:id(.:format)", collection "update_user_settings PATCH /settings/update_user(.:format)" #collection vem sem "id"
      get :password # view, do update_password
      patch :update_user
      patch :update_password
      delete :delete_img_user
    end
  end

  resources :addresses do
    
  end

  # namespace - você Separaria em rotas ficaria tipo admin/category/categories <- SE eu colocar namespace ASSIM "namespace:category e resources :categories dentro"  
  # MAS acho que nao faz sentido agora / tentar fazer depois esse jeito de separar namespace
  # nesse jeito teria um "app>controllers>category>categories_controller.rb" ai criaria o namespace
  namespace :admin do
    root to: "home#index"
    
    resources :categories
    resources :products
  end
  
end

app/views/layouts/userSettings/_menu.html.erb
<ul class="list-group list-group-flush">
  <a href="<%= settings_path %>" class="menu-item-profile">
    <li class="list-group-item">Meu Perfil</li>
  </a>
  <a href="<%= password_settings_path %>" class="menu-item-profile">
    <li class="list-group-item">Alterar senha</li>
  </a>
  <a href="<%= addresses_path %>" class="menu-item-profile">
    <li class="list-group-item">Endereços</li>
  </a>
  <a href="#" class="menu-item-profile">
    <li class="list-group-item">Produtos favoritos</li>
  </a>
</ul>

app/views/layouts/userSettings/_modal_option_img.html.erb
<div class="modal fade" id="confirmationModal"  data-bs-backdrop="static" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmationModalLabel">Escolha Alguma Opção</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Change Img</button>
        <%= button_to "Delete-Img", delete_img_user_settings_path(current_user), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>