config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index" #home ali é controller, index ali é action
  resources :settings, only: [:index] do 
    # member do # cancel_setting DELETE /settings/:id/cancel(.:format) | pode ter varia aquiu seria para deletar um usuario da para brincar com isso
    #   delete :cancel 
    # end

    collection do # member "setting PATCH /settings/:id(.:format)", collection "update_user_settings PATCH /settings/update_user(.:format)" #collection vem sem "id"
      get :password # view, do update_password
      patch :update_user
      patch :update_password
      delete :delete_img_user
    end
  end

  resources :addresses do
    
  end

  # namespace - você Separaria em rotas ficaria tipo admin/category/categories <- SE eu colocar namespace ASSIM "namespace:category e resources :categories dentro"  
  # MAS acho que nao faz sentido agora / tentar fazer depois esse jeito de separar namespace
  # nesse jeito teria um "app>controllers>category>categories_controller.rb" ai criaria o namespace
  namespace :admin do
    root to: "home#index"
    
    resources :categories
    resources :products
  end
  
end

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
      <div class="copyright text-center my-auto">
          <span>Copyright &copy; Your Website 2021</span>
      </div>
  </div>
</footer>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_root_path %>">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">ProgAdmin</div>
    </a>

  <hr class="sidebar-divider my-0">

  <li class="nav-item active">
      <a class="nav-link" href="<%= admin_root_path%>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
  </li>

  <hr class="sidebar-divider">

  <li class="nav-item">
    <a class="nav-link" href="<%= admin_categories_path %>">
        <i class="fa-regular fa-bookmark"></i>
        <span>Categorias</span>
    </a>
  </li>

    <li class="nav-item">
        <a class="nav-link" href="<%= admin_products_path %>">
            <i class="fa-brands fa-product-hunt"></i>
            <span>Produtos</span>
        </a>
    </li>

     <li class="nav-item">
        <a class="nav-link" data-method="delete" href="<%= destroy_user_session_path %>">
            <i class="fa-solid fa-right-from-bracket"></i>
            <span>Sair</span>
        </a>
    </li>

  <li class="nav-item active">
     <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link"  %>
  </li>

  <hr class="sidebar-divider d-none d-md-block">

  <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>

app/views/layouts/admin/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                <%= current_user.present? ? current_user.name : 'Usuário Desconhecido' %>
                </span>
              <%= image_tag 'undraw_profile.svg', class: 'img-profile rounded-circle' %>
          </a>
      </li>
  </ul>
</nav>