config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index" #home ali é controller, index ali é action
  resources :settings, only: [:index] do 
    # member do # cancel_setting DELETE /settings/:id/cancel(.:format) | pode ter varia aquiu seria para deletar um usuario da para brincar com isso
    #   delete :cancel 
    # end

    collection do # member "setting PATCH /settings/:id(.:format)", collection "update_user_settings PATCH /settings/update_user(.:format)" #collection vem sem "id"
      get :password # view, do update_password
      patch :update_user
      patch :update_password
      delete :delete_img_user
    end
  end

  resources :addresses do
    
  end

  # namespace - você Separaria em rotas ficaria tipo admin/category/categories <- SE eu colocar namespace ASSIM "namespace:category e resources :categories dentro"  
  # MAS acho que nao faz sentido agora / tentar fazer depois esse jeito de separar namespace
  # nesse jeito teria um "app>controllers>category>categories_controller.rb" ai criaria o namespace
  namespace :admin do
    root to: "home#index"
    
    resources :categories
    resources :products
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position , presence: true
end

app/controllers/admin/categories_controller.rb
 # testar depois tirar esse module para ver se funciona a validação do "BaseController" sem esse module Admin
 module Admin
  class CategoriesController < BaseController
    before_action :set_category, only: %i[ show edit update destroy ]

    # GET /categories or /categories.json
    def index
      @categories = Category.all
    end

    # GET /categories/1 or /categories/1.json
    def show # chama "before_action" "set_category"
    end

    # GET /categories/new
    def new # esse "def new" é a action new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit # quando eu clico aqui ele chama "before_action" ali que tem o "set_category", lá em baixo ele faz get pelo parametro que vier
    end

    # POST /categories or /categories.json
    def create
      @category = Category.new(category_params)
        if @category.save
          redirect_to admin_categories_path(@category), notice: "Category was successfully created." 
        else
          render :new, status: :unprocessable_entity 
        end
    end

    # PATCH/PUT /categories/1 or /categories/1.json
    def update
      if @category.update(category_params)
        redirect_to admin_categories_path(@category), notice: "Category was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
    end

    # DELETE /categories/1 or /categories/1.json
    def destroy
      @category.destroy!

      respond_to do |format|
        format.html { redirect_to admin_categories_path, notice: "Category was successfully destroyed." }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def category_params
        params.require(:category).permit(:name, :position) # restringindo qual os campo pode vim aqui só esses são aceitos
      end
  end
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= category.position %>
  </p>

</div>

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @category]) do |f| %> <%# esse ':admin' com [] diz que ele é do namespace admin, assim 'admin_categories' %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
    <%# Normalmente por contexto o 'simple_form_for' já sabe qual é a função do botão aqui ele sabe que é um CREATE, mas tem como trocar igual vamos colocar 'Salvar'%>
  </div>
<% end %>

app/views/admin/categories/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %> <%# target: :_top -> não precisa disso %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button 
        type="button" 
        class="btn-close" 
        data-bs-dismiss="modal" 
        aria-label="Close"
        style="background: none; border: none;"
        >
            x
          </button>
        </div>
        <div class="modal-body">
          <%= render "admin/categories/form", category: @category %>
        </div>
      </div>
    </div>
  </div>
<%end %>

app/views/admin/categories/edit.html.erb
<h1 class="h3 mb-4 text-gray-800">Editing category</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <%= render "form", category: @category %>
            </div>
        </div>
    </div>
</div>

app/views/admin/categories/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/categories/form_modal", locals: { category: @category } %> 
<% end %>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="h3 mb-4 text-gray-800">Categories</h1>
<div class="row">
  <div class="col-lg-12">
    <!-- Circle Buttons -->
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Posição</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <%@categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.position %></td>
                <td>
                  <%= link_to "Details", admin_category_path(category), class: 'btn btn-primary' %>
                  <%= link_to "Edit", edit_admin_category_path(category), "data-controller": "admin-modal", class: 'btn btn-secondary' %>
                  <%= link_to "Delete", admin_category_path(category), class: 'btn btn-danger', method: :delete,  data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "New category", new_admin_category_path, "data-controller": "admin-modal", class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<h1 class="h3 mb-4 text-gray-800">New category</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <%= render "form", category: @category %>
            </div>
        </div>
    </div>
</div>

app/views/admin/categories/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/categories/form_modal", locals: { category: @category } %> 
<% end %>

app/views/admin/categories/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Details of the Category</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <%= render @category %>
            </div>
        </div>
    </div>
</div>