config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index" #home ali é controller, index ali é action
  resources :settings, only: [:index] do 
    # member do # cancel_setting DELETE /settings/:id/cancel(.:format) | pode ter varia aquiu seria para deletar um usuario da para brincar com isso
    #   delete :cancel 
    # end

    collection do # member "setting PATCH /settings/:id(.:format)", collection "update_user_settings PATCH /settings/update_user(.:format)" #collection vem sem "id"
      get :password # view, do update_password
      patch :update_user
      patch :update_password
      delete :delete_img_user
    end
  end

  resources :addresses do
    
  end

  # namespace - você Separaria em rotas ficaria tipo admin/category/categories <- SE eu colocar namespace ASSIM "namespace:category e resources :categories dentro"  
  # MAS acho que nao faz sentido agora / tentar fazer depois esse jeito de separar namespace
  # nesse jeito teria um "app>controllers>category>categories_controller.rb" ai criaria o namespace
  namespace :admin do
    root to: "home#index"
    
    resources :categories
    resources :products
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end

  belongs_to :category

  validates :name, :description, :price,  presence: true
end

# - esse foi tirado porque ele automaticamente coloca no front mais era bom deixar aqui validado -CAMPO category_id, e o publish nao foi colocado

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :set_category, only: %i[ show edit update destroy ]

    def index
      @products = Product.all
    end

    def edit # quando eu clico aqui ele chama "before_action" ali que tem o "set_category", lá em baixo ele faz get pelo parametro que vier
    end # quando clicar em salvar, aqui no edit, ele chama "update"

    def new
      authorize Product

      @product = Product.new
    # rescue Pundit::NotAuthorizedError #esse é o jeito "errado" eu fiz do outro jeito que é com "I18n" "jeito certo"
    #   flash[:notice] = "Você só pode cadastrar um produto se tiver uma categoria criada."
    #   redirect_to action: :index

    end # quando chegar aqui ele só está a instacia do product, quando criar em salvar ai sim ele chama 'create'

    def show;end

    def create
      @product = Product.new(product_params)
        if @product.save
          redirect_to admin_products_path(@product), notice: "product was successfully created."
        else
          render :new, status: :unprocessable_entity
        end
    end

    def update
        if @product.update(product_params)
          redirect_to admin_products_path(@product), notice: "product was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
      @product.destroy!

      respond_to do |format|
        format.html { redirect_to admin_products_path, notice: "product was successfully destroyed." }
      end
    end

    private

    def set_category
      @product = Product.find(params[:id]) # params estou pegando tudo que vem depois de "?" oque tiver tem como pegar
    end

    # Only allow a list of trusted parameters through.
    def product_params # autoriazado esse campo para "update, create" via submit
      params.require(:product).permit(:name, :description, :price, :publish, :image, :category_id, :promo, :promo_price) # restringindo qual os campo pode vim aqui só esses são aceitos
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def display_price(product)
    if product.promo?
      content_tag(:div) do
        content_tag(:span, number_to_currency(product.price), class: "text-muted text-decoration-line-through") + " " + 
        content_tag(:span, number_to_currency(product.promo_price))
      end
    else
      content_tag(:span, number_to_currency(product.price))
    end
  end
end  

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %> <%# esse ':admin' com [] diz que ele é do namespace admin, assim 'admin_products' %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :publish %>
    <%= f.input :promo %>
    <%= f.input :promo_price %>
    <%= f.association :category, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
    <%# Normalmente por contexto o 'simple_form_for' já sabe qual é a função do botão aqui ele sabe que é um CREATE, mas tem como trocar igual vamos colocar 'Salvar'%>
  </div>
<% end %>

app/views/admin/products/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %> <%# target: :_top -> não precisa disso %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button 
        type="button" 
        class="btn-close" 
        data-bs-dismiss="modal" 
        aria-label="Close"
        style="background: none; border: none;"
        >
          x
        </button>
      </div>
      <div class="modal-body">
        <%= render "admin/products/form", product: @product %>
      </div>
    </div>
  </div>
</div>
<%end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Imagem:</strong>
    <%= image_tag product.image.variant(:thumb) %>
  </p>

  <p>
    <strong>Descição:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Preço:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= product.publish %>
  </p>

</div>

app/views/admin/products/edit.html.erb
<h1 class="h3 mb-4 text-gray-800">Editing product</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <%= render "form", product: @product %>
            </div>
        </div>
    </div>
</div>

app/views/admin/products/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/products/form_modal", locals: { category: @category } %> 
<% end %>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3 mb-4 text-gray-800">Produts</h1>

<div class="row">
    <div class="col-lg-12">
        <!-- Circle Buttons -->
        <div class="card shadow mb-4">
            <div class="card-body">
              <table class="table table-striped">
                <thead>
                  <th>Nome</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th>Ativo</th>
                </thead>
                <tbody>
                   <%@products.each do |product| %>
                  <tr>
                    <td><%= product.name %></td>
                    <td><%= product.description %></td>
                    <td><%= product.price %></td>
                    <td><%= product.publish %></td>

                    <td>
                      <%= link_to "Details", admin_product_path(product), class: 'btn btn-primary' %>
                      <%= link_to "Edit", edit_admin_product_path(product), data: { controller: "admin-modal" }, class: 'btn btn-secondary' %>
                      <%= link_to "Delete", admin_product_path(product), class: 'btn btn-danger', method: :delete,  data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?' } %>
                    </td>
                   </tr>
                  <% end %>
                </tbody>
              </table>
              <%= link_to "New product", new_admin_product_path, data: { controller: "admin-modal" }, class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>

app/views/admin/products/new.html.erb
<h1 class="h3 mb-4 text-gray-800">New product</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <%= render "form", product: @product %>
            </div>
        </div>
    </div>
</div>

app/views/admin/products/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/products/form_modal", locals: { category: @category } %> 
<% end %>

app/views/admin/products/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Details of the Product</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <%= render @product %>
            </div>
        </div>
    </div>
</div>